title: "psadm.in"
languageCode: "en-us"
baseurl: "https://ps-admin.github.io/"
copyright: "Copyright (c) 2016, JR Bing; all rights reserved."
description: "psadm.in"
metaDataFormat: "yaml"
verbose: false
ignoreCache: true

#pygmentsCodeFences: true
#pygmentsuseclasses: true

#blackfriday:
  #angledQuotes: true
  #fractions: false
  #plainIDAnchors: true
  #extensions:
    #- hardLineBreak

params:
  author: "JR Bing"
